### ISSUE TITLE
Cannot add new themes

### ISSUE THREAD

**Issue by KammutierSpule** [maxrossello/redmine_pluggable_themes#1]
I am using Redmine 4.1.0.stable
I installed https://github.com/maxrossello/redmine_themes
All work fine.

Now if I create a new theme, eg copy the A1

```
cd /opt/bitnami/apps/redmine/htdocs/
bundle install
bundle exec rake redmine:plugins:migrate NAME=redmine_my_theme RAILS_ENV=production
sudo /opt/bitnami/ctlscript.sh restart
```
It installs fine, no errors, but once I select this new theme, it will fail to get access to the .css .js etc files.
That files are on the correct public folder, but for some reason, redmine cannot access to it.

Any idea?

**Comment by maxrossello** [comment]
Have you followed this?

    Edit stylesheets/application.css and change the line (if present)

    @import url(../../../stylesheets/application.css);

to

  
    @import url(/stylesheets/application.css);

**Comment by KammutierSpule** [comment]
Hi Max,
Yes I just copied the A1 example. Even if I place it on the same folder it won't work.
I checked the permission and owner of the files and they look ok.

I noticed that, when I use a theme that works, it is looking for the /stylesheets/application.css on the "root" address. On the cases it fail, it is looking for the files with the address of the plugin (in public folder) (but I'm not sure how it should work)

**Comment by maxrossello** [comment]
Changing the @import is necessary because your plugin's theme folder (in this case the subdir within redmine_themes plugin) is a deeper path, so the relative "../../.." does not hold like it does for the themes installed in the official way. So an absolute path is required (which would work fine for all themes, btw).
This is required for every @import in a theme. Some themes import more than just application.css.
Hope this helps

**Comment by maxrossello** [comment]
I've added a set of stylesheets that get referenced by relative imports and reference absolute paths. So the themes can be added up unmodified.
Any plugin that wishes to do the same can copy/paste the same stylesheets.
